### PR TITLE
Don't start uevent port during tests

### PR DESCRIPTION
**Pull request by krodelin**
A quick fix which allows running tests under Mac OS X.

Fixes issue #34.

### CODE REVIEW

**Comment by fhunleth** [comment]
I can't reproduce this. It looks like there's already code to now start `uevent` on the host (i.e., OSX) at https://github.com/nerves-project/nerves_runtime/blob/v0.10.2/lib/nerves_runtime/application.ex#L32-L45. Or am I misunderstanding?

**Comment by fhunleth** [comment]
I'm feeling like I should have closed #34 a long time ago when the change to not start the GenServers when running on the host was added. However, presumably you hit this, so if you could remind me what I'm forgetting, I'd appreciate it.

**Comment by fhunleth** [comment]
Closing since I don't think this should be needed. Feel free to re-open with more details if it's still a problem.

**Comment by krodelin** [comment]
IMHO there are two different things. Not starting the UEvent GenServer and not starting the uevent port. The code in `application.ex` prevents the Genserver from being started. However this also prevents it from being testable by spoonfeeding messages which appear to come from the port.

My pull prevented the port from being started while still allowing the genserver to run.

**Pull request closed without merging**
