### PR TITLE
Try to call :init.stop on shutdown

### PR DESCRIPTION
**Pull request by fhunleth**
If `:logger` isn't running, then the reboot, shutdown, halt commands
fail. This tries to salvage things by always calling `:init.stop`.

### CODE REVIEW

**Comment by fhunleth** [comment]
@mobileoverlord What do you think of the new changes?

**Comment by mobileoverlord** [comment]
I think it'll still have the same prob. I've seen times where calling `:init.stop` never returns due to an app with an improperly structured supervision tree. I think to properly handle it, we just call `:init.stop`, but in the vm args templates we set the kernel option for `shutdown_timeout`

**Comment by fhunleth** [comment]
In the new case, `:init.stop` can only be called if `cmd("reboot")`, etc., is called. Those commands all set a reboot timer, so it's impossible for `:init.stop` to hang forever.

**Comment by fhunleth** [comment]
I suppose that the return code could be matched on the call to `cmd` just in case `reboot`, `shutdown`, or `halt` fail to run.

**Comment by mobileoverlord** [comment]
Yeah, its a super unlikely case, but if the `cmd("reboot")` call raises, it would still make an attempt to `:init.stop`

**Comment by fhunleth** [comment]
I make some minor tweaks after some additional testing. I think that it's good now.

**Pull request merged**
