### PR TITLE
Find the uevent files and then add

### PR DESCRIPTION
**Pull request by fhunleth**
This changes the uevent discovery process to find all of the uevent
files and then to write "add" to them. Previously, "add" was written to
them while finding them.

The reason that this is ok is because when the discovery process is
started, the uevent port has been started. Therefore, if a device were
to get added during the file discovery process, it would already have
sent a uevent that the uevent port would have seen.

This change appears to noticeably speed up discovery time when combined
with #107 on the Raspberry Pi Zero.

### CODE REVIEW

**Comment by fhunleth** [comment]
My testing on the speed improvement consists of rebooting, and then typing at the iex prompt and watching the responsiveness of the system. Not very scientific, but I'm feeling smaller hiccups instead of the long ones that appeared about a month ago. Mostly, I like the code better, though.

**Comment by fhunleth** [comment]
Thanks for checking. That's my experience as well. It seems like uniprocessors have trouble and it's been affecting the BBB too.

**Comment by ConnorRigby** [comment]
I didn't check on a BBB device, but i suspect it will benefit from this just like RPI0. I remember BBB being pretty slow as well on initial bootup

**Comment by fhunleth** [comment]
Yes - it's cause a most bothersome transient issue with `nerves_uart` where the port process sends a response back to Erlang and it never gets dispatched. This then cause a timeout. Longer timeouts don't fix the problem. However this PR and #107 seem to reduce whatever contention is causing the problems. I am certain the issue will hit me again, but this fixes an immediate issue for me and helps performance, so ¯\_(ツ)_/¯

**Comment by mobileoverlord** [comment]
🎉

**Pull request merged**
